server:
  port: 0

spring:
  application:
    name: TRANSACTION-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/paypal_transactions
    username: root # <-- Change this
    password: root # <-- Change this
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/